### PR TITLE
Removes shaded trees and renames is_shaded to agroforestry_present

### PR DESCRIPTION
**Pull request by simaob**
For BC ToDo: https://basecamp.com/1756858/projects/12446452/todos/274398239 && https://basecamp.com/1756858/projects/12446452/todos/274398440

* Adds migration to update database
* Updates interface text
* Updates forms and rails methods

Requires `rails db:migrate`

### CODE REVIEW

**Comment by mbarrenechea** [comment]
Fix the conflicts please

**Comment by simaob** [comment]
rebased with master. conflicts fixed! 👍

**Comment by mbarrenechea** [comment]
It doesn't seem to be fixed... 💃

**Comment by simaob** [comment]
so many conflicts so little time

**Comment by simaob** [comment]
No more conflicts! :$

**Pull request merged**
